// ...existing code...
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatDialogModule } from '@angular/material/dialog';
import { NgModule } from '@angular/core';

@NgModule({
  // ...existing code...
  imports: [
    // ...existing imports...
    BrowserAnimationsModule,
    MatDialogModule,
  ],
  // ...existing code...
})
export class AppModule {}
// ...existing code...